// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batorment_v2_raids.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const softDeleteOldRaids = `-- name: SoftDeleteOldRaids :execresult
UPDATE batorment_v2.raids 
SET deleted_at = NOW(), updated_at = NOW() 
WHERE created_at < $1 
AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOldRaids(ctx context.Context, createdAt pgtype.Timestamp) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, softDeleteOldRaids, createdAt)
}
