// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batorment_v2_students.sql

package postgres

import (
	"context"
)

const insertStudentData = `-- name: InsertStudentData :exec
INSERT INTO batorment_v2.students (student_id, name_ko, name_ja, search_keyword, detail, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (student_id) DO UPDATE SET 
    name_ko = EXCLUDED.name_ko,
    name_ja = EXCLUDED.name_ja,
    search_keyword = EXCLUDED.search_keyword,
    detail = EXCLUDED.detail,
    updated_at = NOW()
`

type InsertStudentDataParams struct {
	StudentID     int32    `json:"student_id"`
	NameKo        string   `json:"name_ko"`
	NameJa        string   `json:"name_ja"`
	SearchKeyword []string `json:"search_keyword"`
	Detail        []byte   `json:"detail"`
}

func (q *Queries) InsertStudentData(ctx context.Context, arg InsertStudentDataParams) error {
	_, err := q.db.Exec(ctx, insertStudentData,
		arg.StudentID,
		arg.NameKo,
		arg.NameJa,
		arg.SearchKeyword,
		arg.Detail,
	)
	return err
}
