// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contents.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContents = `-- name: GetContents :one
SELECT content_id, start_date FROM batorment_v3.contents WHERE content_id = $1
`

type GetContentsRow struct {
	ContentID string             `json:"content_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
}

func (q *Queries) GetContents(ctx context.Context, contentID string) (GetContentsRow, error) {
	row := q.db.QueryRow(ctx, getContents, contentID)
	var i GetContentsRow
	err := row.Scan(&i.ContentID, &i.StartDate)
	return i, err
}
