// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contents.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContentByID = `-- name: GetContentByID :one
SELECT content_id, start_date FROM batorment_v3.contents WHERE content_id = $1
`

type GetContentByIDRow struct {
	ContentID string             `json:"content_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
}

func (q *Queries) GetContentByID(ctx context.Context, contentID string) (GetContentByIDRow, error) {
	row := q.db.QueryRow(ctx, getContentByID, contentID)
	var i GetContentByIDRow
	err := row.Scan(&i.ContentID, &i.StartDate)
	return i, err
}

const listContentIDs = `-- name: ListContentIDs :many
SELECT content_id FROM batorment_v3.contents WHERE deleted_at IS NULL
`

func (q *Queries) ListContentIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listContentIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content_id string
		if err := rows.Scan(&content_id); err != nil {
			return nil, err
		}
		items = append(items, content_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentIDsWithStartDate = `-- name: ListContentIDsWithStartDate :many
SELECT content_id, start_date FROM batorment_v3.contents WHERE deleted_at IS NULL ORDER BY start_date ASC
`

type ListContentIDsWithStartDateRow struct {
	ContentID string             `json:"content_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
}

func (q *Queries) ListContentIDsWithStartDate(ctx context.Context) ([]ListContentIDsWithStartDateRow, error) {
	rows, err := q.db.Query(ctx, listContentIDsWithStartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentIDsWithStartDateRow{}
	for rows.Next() {
		var i ListContentIDsWithStartDateRow
		if err := rows.Scan(&i.ContentID, &i.StartDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentsForRaidList = `-- name: ListContentsForRaidList :many
SELECT content_id, title, top_level FROM batorment_v3.contents WHERE deleted_at IS NULL ORDER BY start_date ASC
`

type ListContentsForRaidListRow struct {
	ContentID string   `json:"content_id"`
	Title     string   `json:"title"`
	TopLevel  TopLevel `json:"top_level"`
}

func (q *Queries) ListContentsForRaidList(ctx context.Context) ([]ListContentsForRaidListRow, error) {
	rows, err := q.db.Query(ctx, listContentsForRaidList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentsForRaidListRow{}
	for rows.Next() {
		var i ListContentsForRaidListRow
		if err := rows.Scan(&i.ContentID, &i.Title, &i.TopLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
