// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: i18n.sql

package postgres

import (
	"context"
)

const getI18n = `-- name: GetI18n :one
SELECT category, key, name_ko, name_ja, name_en, created_at, updated_at FROM batorment_v3.i18n WHERE category = $1 AND key = $2
`

type GetI18nParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
}

func (q *Queries) GetI18n(ctx context.Context, arg GetI18nParams) (BatormentV3I18n, error) {
	row := q.db.QueryRow(ctx, getI18n, arg.Category, arg.Key)
	var i BatormentV3I18n
	err := row.Scan(
		&i.Category,
		&i.Key,
		&i.NameKo,
		&i.NameJa,
		&i.NameEn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getI18nByCategory = `-- name: GetI18nByCategory :many
SELECT category, key, name_ko, name_ja, name_en, created_at, updated_at FROM batorment_v3.i18n WHERE category = $1
`

func (q *Queries) GetI18nByCategory(ctx context.Context, category string) ([]BatormentV3I18n, error) {
	rows, err := q.db.Query(ctx, getI18nByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatormentV3I18n{}
	for rows.Next() {
		var i BatormentV3I18n
		if err := rows.Scan(
			&i.Category,
			&i.Key,
			&i.NameKo,
			&i.NameJa,
			&i.NameEn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertI18n = `-- name: UpsertI18n :exec
INSERT INTO batorment_v3.i18n (category, key, name_ko, name_ja, name_en, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (category, key) DO UPDATE SET
    name_ko = EXCLUDED.name_ko,
    name_ja = EXCLUDED.name_ja,
    name_en = EXCLUDED.name_en,
    updated_at = NOW()
`

type UpsertI18nParams struct {
	Category string `json:"category"`
	Key      string `json:"key"`
	NameKo   string `json:"name_ko"`
	NameJa   string `json:"name_ja"`
	NameEn   string `json:"name_en"`
}

func (q *Queries) UpsertI18n(ctx context.Context, arg UpsertI18nParams) error {
	_, err := q.db.Exec(ctx, upsertI18n,
		arg.Category,
		arg.Key,
		arg.NameKo,
		arg.NameJa,
		arg.NameEn,
	)
	return err
}
