// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BatormentV2Raid struct {
	RaidID    string           `json:"raid_id"`
	Name      string           `json:"name"`
	ShortName string           `json:"short_name"`
	Status    string           `json:"status"`
	TopLevel  string           `json:"top_level"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}

type BatormentV2Student struct {
	StudentID     int32            `json:"student_id"`
	NameKo        string           `json:"name_ko"`
	NameJa        string           `json:"name_ja"`
	SearchKeyword []string         `json:"search_keyword"`
	Detail        []byte           `json:"detail"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type BatormentV2Video struct {
	ID                int32            `json:"id"`
	RaidID            string           `json:"raid_id"`
	Title             string           `json:"title"`
	YoutubeUrl        string           `json:"youtube_url"`
	Score             int32            `json:"score"`
	AiGeneratedDetail []byte           `json:"ai_generated_detail"`
	ParsedDetail      []byte           `json:"parsed_detail"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}
