// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: presents.sql

package postgres

import (
	"context"
)

const insertPresent = `-- name: InsertPresent :exec
INSERT INTO batorment_v3.presents (present_id, name_ko, rarity, tags, exp_value, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (present_id) DO UPDATE SET 
    name_ko = EXCLUDED.name_ko,
    rarity = EXCLUDED.rarity,
    tags = EXCLUDED.tags,
    exp_value = EXCLUDED.exp_value,
    updated_at = NOW()
`

type InsertPresentParams struct {
	PresentID int32    `json:"present_id"`
	NameKo    string   `json:"name_ko"`
	Rarity    string   `json:"rarity"`
	Tags      []string `json:"tags"`
	ExpValue  int32    `json:"exp_value"`
}

func (q *Queries) InsertPresent(ctx context.Context, arg InsertPresentParams) error {
	_, err := q.db.Exec(ctx, insertPresent,
		arg.PresentID,
		arg.NameKo,
		arg.Rarity,
		arg.Tags,
		arg.ExpValue,
	)
	return err
}
