// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	InsertStudentData(ctx context.Context, arg InsertStudentDataParams) error
	SoftDeleteOldRaids(ctx context.Context, createdAt pgtype.Timestamp) (pgconn.CommandTag, error)
	UpdateRaidStatusToComplete(ctx context.Context, raidID string) error
}

var _ Querier = (*Queries)(nil)
