// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetContents(ctx context.Context, contentID string) (GetContentsRow, error)
	InsertPresent(ctx context.Context, arg InsertPresentParams) error
	InsertStudentData(ctx context.Context, arg InsertStudentDataParams) error
}

var _ Querier = (*Queries)(nil)
