// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"
)

type Querier interface {
	InsertStudentData(ctx context.Context, arg InsertStudentDataParams) error
}

var _ Querier = (*Queries)(nil)
