// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: youtube_analysis.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getVerifiedYoutubeAnalysisByRaidID = `-- name: GetVerifiedYoutubeAnalysisByRaidID :many
SELECT id, video_id, raid_id, analysis_result, analysis_type, version, is_verified, created_at, updated_at
FROM batorment_v3.youtube_analysis
WHERE raid_id = $1
  AND is_verified = true
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetVerifiedYoutubeAnalysisByRaidIDRow struct {
	ID             int32              `json:"id"`
	VideoID        string             `json:"video_id"`
	RaidID         string             `json:"raid_id"`
	AnalysisResult []byte             `json:"analysis_result"`
	AnalysisType   AnalysisType       `json:"analysis_type"`
	Version        int32              `json:"version"`
	IsVerified     bool               `json:"is_verified"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetVerifiedYoutubeAnalysisByRaidID(ctx context.Context, raidID string) ([]GetVerifiedYoutubeAnalysisByRaidIDRow, error) {
	rows, err := q.db.Query(ctx, getVerifiedYoutubeAnalysisByRaidID, raidID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVerifiedYoutubeAnalysisByRaidIDRow{}
	for rows.Next() {
		var i GetVerifiedYoutubeAnalysisByRaidIDRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.RaidID,
			&i.AnalysisResult,
			&i.AnalysisType,
			&i.Version,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
